#设置端口
server:
  port: 8080
  max-http-header-size: 1024000
#配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/athlete_mode?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: JH220396a
    driver-class-name: com.mysql.cj.jdbc.Driver
    thymeleaf:
      cache: false
      prefix: classpath:/static/*
#映射文件
mybatis:
  mapper-locations: classpath:/mapper/*/*.xml
# 配置pagehelper参数
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
